version: '3.7'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./data/mysql/:/var/lib/mysql